import { SessionProvider } from "next-auth/react"
import Header from "../components/header"
import AuthSession from "../components/authSession"
import "../styles/global.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthSession>
        <Header />
        {children}
        </AuthSession>
      </body>
    </html>
  )
}
